### ISSUE TITLE
Blog post about keynote at AMCIS

### ISSUE THREAD

**Issue by sbrunswi** [RCODI/rcodi-blog#46]
**Task**
Write a blog post about Dr. Brunswicker's talk at AMCIS 2021. https://amcis2021.aisconferences.org/

- [ ] Sabine' to provide title of talk
- [ ] Bryan to draft post
- [ ] Bryan et al to share real time information about the talk

**Comment by sbrunswi** [comment]
I did not do this due to the loss/death of my mother. So it can be closed.
